### ISSUE TITLE
Error after running  `npm run web`

### ISSUE THREAD

**Issue by ariolaclint** [hossein-zare/react-native-chunk-upload#1]
react-native-chunk-upload\node_modules\react-native-fs\FS.common.js: Unexpected token, expected "," (30:29)

  28 | };
  29 | 
> 30 | var normalizeFilePath = (path: string) => (path.startsWith('file://') ? path.slice(7) : path);
     |                              ^
  31 | 
  32 | type MkdirOptions = {
  33 |   NSURLIsExcludedFromBackupKey?: boolean; // iOS only

**Comment by hossein-zare** [comment]
Hello,
It's an error from **https://github.com/itinance/react-native-fs** not this package.
