### ISSUE TITLE
missing semicolon error

### ISSUE THREAD

**Issue by hosein-yarzade** [hossein-zare/react-native-chunk-upload#2]
i use this package Basic Usage in my RN project  and show this error : missing semicolon error in this line ==>

upload(file, next, retry, unlink) "missing semicolon error "{ ...

what i do??
helpe me plz

**Comment by hossein-zare** [comment]
Hello,

Please send me your code.
Most likely you've been using it in a functional component.

**Comment by hosein-yarzade** [comment]
class App extends Component {
   constructor () {
     super();
     this.state = {
       videoFile: {},
     };
   }

 sendVideo=()=>{
     const chunk = new ChunkUpload({
       path: this.state.videoFile.path, // Path to the file
       size: 10024, // Chunk size (must be multiples of 3)
       fileName: this.state.videoFile.fileName, // Original file name
       fileSize: this.state.videoFile.size, // Original file size

       // Errors
       onFetchBlobError: (e) => console.log(e),
       onWriteFileError: (e) => console.log(e),
     });
     chunk.digIn(this.upload.bind(this));

      upload(file, next, retry, unlink){
       const body = new FormData();

       body.append('video', file.blob); // param name

       Axios.post('vod/submitStep1', body, {
         headers: {
           'Content-Type': 'multipart/form-data',
           Accept: 'application/json',
           'x-chunk-number': file.headers['x-chunk-number'],
           'x-chunk-total-number': file.headers['x-chunk-total-number'],
           'x-chunk-size': file.headers['x-chunk-size'],
           'x-file-name': file.headers['x-file-name'],
           'x-file-size': file.headers['x-file-size'],
           'x-file-identity': file.headers['x-file-identity'],
         },
       })
         .then((response) => {
           switch (response.status) {

             case 200:
               console.log(response.data);
               break;
             case 201:
               console.log(`${response.data.progress}% uploaded...`);
               next();
               break;
           }
         })
         .catch((error) => {
           if (error.response) {
             if ([400, 404, 415, 500, 501].includes(error.response.status)) {
               console.log(error.response.status, 'Failed to upload the chunk.');

               unlink(file.path);
             } else if (error.response.status === 422) {
               console.log('Validation Error', error.response.data);

               unlink(file.path);
             } else {
               console.log('Re-uploading the chunk...');
               retry();
             }
           } else {
             console.log('Re-uploading the chunk...');

             retry();
           }
         });
     }
   }

> Hello,
> 
> Please send me your code.
> Most likely you've been using it in a functional component.

here you are

**Comment by hossein-zare** [comment]
Add a `}` before the `upload` function.

```javascript
sendVideo = () => {
    const chunk = new ChunkUpload({

      path: this.state.videoFile.path, // Path to the file
      size: 10024, // Chunk size (must be multiples of 3)
      fileName: this.state.videoFile.fileName, // Original file name
      fileSize: this.state.videoFile.size, // Original file size
      // Errors
      onFetchBlobError: (e) => console.log(e),
      onWriteFileError: (e) => console.log(e),
    });
    chunk.digIn(this.upload.bind(this));
} // You've forgotten a closing curly brace

**Comment by hosein-yarzade** [comment]
thanks i got it
