### ISSUE TITLE
No such file 

### ISSUE THREAD

**Issue by hosein-yarzade** [hossein-zare/react-native-chunk-upload#3]
Hi
i have this error >

onFetchBlobError=> Error: No such file 'content://com.android.providers.media.documents/document/video%3A25'

i use react-native-document-picker package for get video file path 
actully i use emulator and debug mode

sendVideo=()=>{
     const file = this.state.videoFile
     const chunk = new ChunkUpload({
       path: file.uri, // Path to the file
       size: 10095, // Chunk size (must be multiples of 3)
       fileName: file.name, // Original file name
       fileSize: file.size, // Original file size

       // Errors
       onFetchBlobError: (e) =>  console.log('onFetchBlobError=>', e), //this line
       onWriteFileError: (e) =>  console.log('onWriteFileError=>', e),
     });
     chunk.digIn(this.upload.bind(this));

   }

and this is file state

fileCopyUri: "content://com.android.providers.media.documents/document/video%3A25"
name: "file_example_MP4_1920_18MG.mp4"
size: 17839845
type: "video/mp4"
uri: "content://com.android.providers.media.documents/document/video%3A25"

**Comment by hossein-zare** [comment]
Hi, Read: https://stackoverflow.com/questions/52423067/how-to-get-absolute-path-of-a-file-in-react-native
