### ISSUE TITLE
File does not exist at path : onFetchBlobError

### ISSUE THREAD

**Issue by adrienfloor** [hossein-zare/react-native-chunk-upload#6]
Hey @hossein-zare 

Thank you for the work here. I'm sorry but I've been looking into the other issues and pretty much googled everything I could on the subject but I keep getting the fetch blob error on iOS : 

```
Error: File does not exist at path file://var/mobile/Containers/Data/Application/673C5AA2-C147-4FB8-B7D5-7A7F8E72BFAE/tmp/IMG_1975.mov
```
I've been trying with paths like : 
- file://var/mobile/Containers/...
- file:///var/mobile/Containers/...
- /var/mobile/Containers/...
- var/mobile/Containers/...

Looks like the fetchblob module is automatically adding "file://"

I'm stuck here and can't make use of your lib. Do you have any idea of what I could do ? I've checked all the stackoverflow pieces and github issues.

Thank you very much 🙌🏼

**Comment by hossein-zare** [comment]
Hi @adrienfloor ,
I just released **react-native-chunk-upload@2.0.2** for the error.

**Comment by adrienfloor** [comment]
Awesome, I'll try it right now. Thank you very much !

**Comment by adrienfloor** [comment]
Error is gone, thank you 👍
